### ISSUE TITLE
九宫和八门无法显示

### ISSUE THREAD

**Issue by glass4pk** [qfdk/qimen#2]
![image](https://user-images.githubusercontent.com/1888886/80688572-95eec180-8afe-11ea-9b77-f8f17e9a52fe.png)

**Comment by qfdk** [comment]
还没有弄完。。。

**Comment by glass4pk** [comment]
我用mpvue重新写了个小程序，准备扔上来
改了很多……无法在你这个程序上改了

对了，你这里引用的节气和寻找阴阳遁局有点问题，节气不对，遁局的上中下元我用的拆解法来求，跟你用的15日法有点出入，可以看看

**Comment by qfdk** [comment]
@glass4pk 感谢，因为之前也是花了点儿时间，最近有空打算重写。

其中节气分为很多种方法，你的是拆补，我的是茅山，还有一种是致润。这个也是一开始入门奇门的时候写了个程序了解下排盘原理。其实九星 这些有排，但是去掉了。感觉算反不大对，有空重新搞一下。
